# services:
#   langfuse-server:
#     image: langfuse/langfuse:latest
# #    depends_on:
# #      db:
# #        condition: service_healthy
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     environment:
#       - DATABASE_PORT=${DATABASE_PORT:-5432}
#       - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
#       - DATABASE_PASSWORD=${DATABASE_PASSWORD:-Letsfindout123*#}
#       - DATABASE_NAME=${DATABASE_NAME:-postgres}
#       - DATABASE_HOST=${DATABASE_HOST:-host.docker.internal}
#       - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-secret}
#       - SALT=${SALT:-salt}
#       - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
#       - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
#       - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}



services:
  langfuse-server:
    image: langfuse/langfuse:latest
    # depends_on:
    #   db:
    #     condition: service_healthy
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=mlabhishek
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=langfuse1
      - DATABASE_HOST=host.docker.internal
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-secret}
      - SALT=${SALT:-salt}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}